version: "3.5"

services:
  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      TYPEORM_HOST: database

  database:
      container_name: app_mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_TCP_PORT: ${TYPEORM_PORT}
        MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
        MYSQL_DATABASE: ${TYPEORM_DATABASE}
      ports:
      - 3308:${TYPEORM_PORT}
    